name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres && cargo sqlx prepare --check && cargo build --release
      - name: Run tests
        run: cargo test --verbose

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: target/release/mooze-dealer
